# Verifies the seed fixture tree:
#   1. every payload in objects.json exists and matches its sha256 checksum,
#   2. object-corrupt's declaredSha256 is intentionally wrong (negative fixture),
#   3. regeneration is idempotent (regenerate into a temp dir, diff with tree).
# Exit code 0 = all good; nonzero = drift or missing fixtures.

$ErrorActionPreference = 'Stop'
$version = 'v1'
$root = Join-Path $PSScriptRoot '..\fixtures'
$fixtureDir = Join-Path $root $version
$payloadDir = Join-Path $fixtureDir 'payloads'

$objects = Get-Content (Join-Path $fixtureDir 'objects.json') -Raw | ConvertFrom-Json
$failures = @()

foreach ($obj in $objects.objects) {
    $path = Join-Path $fixtureDir $obj.payload
    if (-not (Test-Path $path)) {
        $failures += "MISSING payload for $($obj.uid): $($obj.payload)"
        continue
    }
    $actual = (Get-FileHash -Algorithm SHA256 $path).Hash.ToLower()
    if ($actual -ne $obj.sha256) {
        $failures += "CHECKSUM mismatch for $($obj.uid): expected $($obj.sha256), got $actual"
    }
    if ($obj.PSObject.Properties.Name -contains 'declaredSha256') {
        if ($obj.declaredSha256 -eq $obj.sha256) {
            $failures += "NEGATIVE FIXTURE BROKEN: $($obj.uid) declaredSha256 must differ from the real checksum"
        }
    }
    Write-Host "ok  $($obj.uid) ($($obj.sizeBytes) B)"
}

# Idempotency: regenerate into the real tree — bytes must not change.
$script = Join-Path $PSScriptRoot 'regenerate.ps1'
$snapshot = @{}
Get-ChildItem $payloadDir -File | ForEach-Object {
    $snapshot[$_.Name] = (Get-FileHash -Algorithm SHA256 $_.FullName).Hash
}
$null = & $script
foreach ($f in Get-ChildItem $payloadDir -File) {
    $after = (Get-FileHash -Algorithm SHA256 $f.FullName).Hash
    if ($snapshot[$f.Name] -ne $after) {
        $failures += "REGENERATION NOT IDEMPOTENT for $($f.Name)"
    }
}
Write-Host "idempotency check passed ($($snapshot.Count) payloads regenerated byte-identical)"

if ($failures.Count -gt 0) {
    Write-Host "`nFAILED:"
    $failures | ForEach-Object { Write-Host "  - $_" }
    exit 1
}
Write-Host "`nAll seed fixtures verified."
